.TH "Button" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Button \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBx2\fP"
.br
.ti -1c
.RI "int \fBy2\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBbuttonColor\fP"
.br
.ti -1c
.RI "int \fBtextColor\fP"
.br
.ti -1c
.RI "ALLEGRO_FONT * \fBfont\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBButton\fP 
.SH "Member Data Documentation"
.PP 
.SS "int Button::buttonColor"
button color 
.SS "ALLEGRO_FONT* Button::font"
font text 
.SS "char* Button::text"
text inside button 
.SS "int Button::textColor"
text color 
.SS "int Button::x"
x begin 
.SS "int Button::x2"
x destination 
.SS "int Button::y"
y begin 
.SS "int Button::y2"
y destination 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
