.TH "Enemy" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "int \fBrad\fP"
.br
.ti -1c
.RI "bool \fBisLive\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "int \fBenemyType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBEnemy\fP Game's obstacle 
.SH "Member Data Documentation"
.PP 
.SS "int Enemy::enemyType"
what enemy is 
.SS "bool Enemy::isLive"
if enemy is still alive 
.SS "int Enemy::rad"
radius of enemy 
.SS "bool Enemy::reverse"
if enemy is reverse 
.SS "float Enemy::x"
x position 
.SS "float Enemy::y"
y position 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
