.TH "Flag" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flag \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBspeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFlag\fP Victory flag 
.SH "Member Data Documentation"
.PP 
.SS "int Flag::speed"
movement speed 
.SS "int Flag::x"
x position 
.SS "int Flag::y"
y position 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
