.TH "Image" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ALLEGRO_BITMAP * \fBimage\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBy_displacement\fP"
.br
.ti -1c
.RI "int \fBspeed\fP"
.br
.ti -1c
.RI "bool \fBisShow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBImage\fP image 
.SH "Member Data Documentation"
.PP 
.SS "int Image::height"
height of image 
.SS "ALLEGRO_BITMAP* Image::image"
allegro bitmap image 
.SS "bool Image::isShow"
if image is showed 
.SS "int Image::speed"
movement speed of image 
.SS "int Image::width"
width of image 
.SS "int Image::x"
position x 
.SS "int Image::y"
position y 
.SS "int Image::y_displacement"
y displacement for same image 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
