.TH "Images" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Images \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImage\fP * \fBimage\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBname\fP"
.br
.ti -1c
.RI "int \fBhowShowed\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBImages\fP group of images 
.SH "Member Data Documentation"
.PP 
.SS "int Images::howShowed = 0"
how images are showed 
.SS "\fBImage\fP* Images::image"
images of the group 
.SS "int Images::name"
name of group 
.SS "int Images::size"
number of images 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
