.TH "/home/simone/Developer/Project/eclipse/Run Circlest, Run/bin/headers/io.h" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/simone/Developer/Project/eclipse/Run Circlest, Run/bin/headers/io.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsaveToFile\fP (int data, const char file[])"
.br
.ti -1c
.RI "bool \fBloadFromFile\fP (int &data, const char file[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool loadFromFile (int &data, const charfile[])"
Load data from file 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP integer data to save the load data 
.br
\fIfile\fP file from load data 
.RE
.PP
\fBReturns:\fP
.RS 4
true if success () 
.RE
.PP

.SS "bool saveToFile (intdata, const charfile[])"
Save data to file 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP integer data to save 
.br
\fIfile\fP file to save data 
.RE
.PP
\fBReturns:\fP
.RS 4
true if success 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBloadFromFile()\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
