.TH "Player" 3 "Mon Oct 12 2015" "Run Cirrest, Run" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcx\fP"
.br
.ti -1c
.RI "int \fBcy\fP"
.br
.ti -1c
.RI "int \fBrad\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBx2\fP"
.br
.ti -1c
.RI "int \fBy2\fP"
.br
.ti -1c
.RI "bool \fBisLive\fP"
.br
.ti -1c
.RI "int \fBjumpHeight\fP"
.br
.ti -1c
.RI "bool \fBisJumping\fP"
.br
.ti -1c
.RI "bool \fBisReverseJumping\fP"
.br
.ti -1c
.RI "int \fBjumpSpeed\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPlayer\fP Game's hero 
.SH "Member Data Documentation"
.PP 
.SS "int Player::cx"
center x 
.SS "int Player::cy"
center y 
.SS "bool Player::isJumping"
if player is jumping 
.SS "bool Player::isLive"
if player is still alive 
.SS "bool Player::isReverseJumping"
if player is reverse jumping 
.SS "int Player::jumpHeight"
max height of player jump 
.SS "int Player::jumpSpeed"
speed of player jump 
.SS "int Player::rad"
radius of player 
.SS "int Player::score"
best score of arcade mode 
.SS "int Player::x"
x left 
.SS "int Player::x2"
x right 
.SS "int Player::y"
y top 
.SS "int Player::y2"
y bottom 

.SH "Author"
.PP 
Generated automatically by Doxygen for Run Cirrest, Run from the source code\&.
